apiVersion: v1
kind: Secret

metadata:
  name: taskflow-secret
  namespace: taskflow

type: Opaque

stringData:
  USER_MONGO_URI: "mongodb+srv://devops-task-management-database:ajaytaskmanagement1@cluster0.hnwwy0c.mongodb.net/?appName=Cluster0"

  TASK_MONGO_URI: "mongodb+srv://devops-task-management-database:ajaytaskmanagement1@cluster0.hnwwy0c.mongodb.net/?appName=Cluster0"

  JWT_SECRET: "mysecretkey_fordtmd"