apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service
  namespace: taskflow
  labels:
    app: user-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service
          image: ajayapst/taskflow-user-service:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: USER_SERVICE_PORT

            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: JWT_EXPIRES_IN

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: NODE_ENV

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: taskflow-secret
                  key: USER_MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskflow-secret
                  key: JWT_SECRET

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"